title: My WildCat Studios Portfolio
description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: "" # leave empty since this is your user page
url: "https://sdjq89we.github.io" # replace YOURUSERNAME with your GitHub username
theme: jekyll-theme-hacker # replace minima with your chosen theme from the list
